apiVersion: v1
kind: Secret
metadata:
  name: bob-inf-credentials
  namespace: sre-demo
  labels:
    app: bob-shell-job
type: Opaque
stringData:
  BOBSHELL_API_KEY: "bob_onprem_bob-apikey_4PWNNSgW2CMcVpDxUBEUvmVrexqeEBMGgUe2xxqFRWtPnjkHUMPh94R8dFzqC857vJT2aWbg2z7fy53L5RUsCWmv_HjauEWMMC7xqcSpfUq9vafg7wYKoFatEb241n9BZTQCi"
  BOB_GATEWAY_URL: "https://api.bob.ibm-bob.apps.itz-h7532y.infra01-lb.tok04.techzone.ibm.com"
